---
# tasks file for gvisor_install
- name: Download gVisor binaries
  ansible.builtin.include_tasks: get_binaries.ansible.yml
- name: Setup gVisor binaries
  ansible.builtin.include_tasks: setup_binaries.ansible.yml
- name: Run install command on gVisor binaries
  ansible.builtin.include_tasks: reload_verify.ansible.yml

